version: '3.9'
services:
  safety-riding:
    container_name: safety-riding
    restart: always
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    command: node ace serve --watch
